#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pbr
Version  : 3.1.1
Release  : 61
URL      : https://pypi.debian.net/pbr/pbr-3.1.1.tar.gz
Source0  : https://pypi.debian.net/pbr/pbr-3.1.1.tar.gz
Summary  : Python Build Reasonableness
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: pbr-bin
Requires: pbr-python3
Requires: pbr-license
Requires: pbr-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
============

%package bin
Summary: bin components for the pbr package.
Group: Binaries
Requires: pbr-license

%description bin
bin components for the pbr package.


%package license
Summary: license components for the pbr package.
Group: Default

%description license
license components for the pbr package.


%package python
Summary: python components for the pbr package.
Group: Default
Requires: pbr-python3

%description python
python components for the pbr package.


%package python3
Summary: python3 components for the pbr package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pbr package.


%prep
%setup -q -n pbr-3.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1529115705
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 --verbose py2 || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/pbr
cp LICENSE %{buildroot}/usr/share/doc/pbr/LICENSE
cp pbr/tests/testpackage/LICENSE.txt %{buildroot}/usr/share/doc/pbr/pbr_tests_testpackage_LICENSE.txt
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pbr

%files license
%defattr(-,root,root,-)
/usr/share/doc/pbr/LICENSE
/usr/share/doc/pbr/pbr_tests_testpackage_LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
